### PR TITLE
EASTL_CT_ASSET: avoid conflicting with user definition

### PR DESCRIPTION
**Pull request by codyps**

### CODE REVIEW

**Comment by BSVino** [comment]
This looks functionally identical. Can you give an example of why it's useful?

**Comment by codyps** [comment]
It isn't functionally identical. With the current code, if the user tries to define EASTL_CT_ASSERT(), EASTL attempts to provide the version that is a nop. Note the location of the `#else` and which `#if`s it applies to.

**Comment by BSVino** [comment]
Ah, I missed the #else. Got it thanks :)

**Comment by codyps** [comment]
No problem. Thanks for merging :+1:

**Pull request merged**
