### PR TITLE
push_back(void) requires the object's constructor to have a default over...

### PR DESCRIPTION
**Pull request by BSVino**
...load with no arguments. Rewrote the function to remove that dependency.

### CODE REVIEW

**Comment by BSVino** [comment]
Thank you!

Let me know if you need help maintaining EASTL's community branch. I use it quite a bit in my work.

**Comment by paulhodge** [comment]
Sure! Actually I would love help; I don't use this library myself these days. I would love to transfer project ownership over to you if you want. Or I can add you as a contributer to my fork? Whichever you want, let me know.

**Comment by BSVino** [comment]
I think it's better that the repository stay where it is since there are so many references to it in many places on the nets, so it's probably best that I'm just a contributor.

**Comment by paulhodge** [comment]
Okay it is done, feel free to make changes. Let me know if I need to do anything else

**Comment by BSVino** [comment]
Sounds great, thanks!

**Pull request merged**
