### PR TITLE
make EASTL testable using travis-ci

### PR DESCRIPTION
**Pull request by take-cheeze**

### CODE REVIEW

**Comment by BSVino** [comment]
Give me a few days to look this over.

**Comment by BSVino** [comment]
Sorry it took so long. :)

**Comment by take-cheeze** [comment]
Thanks for the merge.
In addition can you enable travis of this repo?

**Comment by BSVino** [comment]
Can I? Not familiar with travis. What do I do?

**Comment by take-cheeze** [comment]
You need admin.
So @paulhodge have to do it...
Though you can try it out in your repo.
1. go https://travis-ci.org/
2. login with github account
3. go profile
4. turn on the repository you want to enable travis

**Comment by BSVino** [comment]
Yeah I tried and it wouldn't let me. We'll see if Paul comes around.

**Comment by paulhodge** [comment]
Okay I just enabled the build on travis-ci.org, looks like it's all working:

https://travis-ci.org/paulhodge/EASTL

**Pull request merged**
